%YAML 1.1
# ^-- ATTN: [2019-12-31] If you use a later version, Github will fail
#     with a bogus error message "You have an error in your yaml syntax".
# -*- coding: UTF-8, tab-width: 2 -*-
---

on:
  push:
    branches:
      - 'build-*'


jobs:
  job_build_on_ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: mk-pmb/github-ci-util-2405-pmb/act/install@experimental
      - run: ghciu ./run_in_armhf_docker.sh

      - name: 'Gather release files'
        id: gather
        if: always()
        run: ./gather_release_files.sh

      - name: 'Publish release'
        if: always()
        id: rls
        uses: ncipollo/release-action@main
        with:
          allowUpdates: True
          artifactErrorsFailBuild: True
          artifacts: 'release/*'
          bodyFile: '.rlsbody.txt'
          # ^-- Using `body: ''` resulted in GitHub showing an empty
          #     release body in the release editor, but nonetheless
          #     displaying an outdated commit message on the release
          #     info page.
          makeLatest: False
          prerelease: True
          removeArtifacts: True # Remove old files from release.
          commit: '${{ github.sha }}'
          tag: '${{ steps.gather.outputs.tag }}'

      - name: 'Report the release URL'
        if: always()
        run: 'echo "$MSG" >>"$GITHUB_STEP_SUMMARY"'
        env:
          MSG: >
            [Release page for `${{ steps.gather.outputs.tag
            }}`](${{ steps.rls.outputs.html_url }})




...
